services:
  - type: web
    name: gag-dashboard
    plan: free
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: RENDER
        value: 'true'
      - key: PORT
        value: '10000'
